kcl_options:
  - key: argo_namespace
    value: argocd-custom-ns
  - key: application_namespaces
    value:
      - app1
      - app2
  - key: argo_version
    value: v2.13.2
  - key: output_folder
    value: "../argocd"
  - key: repo_url
    value: "https://github.com/obeleh/argocd-namespaced-install.git"
  - key: bootstrap_namespaces
    value: true
  - key: bootstrap_crds
    value: true