apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd-custom-ns
  name: app1
spec:
  generators:
    - git:
        repoURL: https://github.com/obeleh/argocd-namespaced-install.git
        revision: main
        directories:
          - path: argocd/projects/app1/workloads/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: app1
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/obeleh/argocd-namespaced-install.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: app1