---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app1
  name: argocd-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: app1
  name: argocd-role-binding
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd-custom-ns
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app1
  namespace: argocd-custom-ns
spec:
  destinations:
    - namespace: app1
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd-custom-ns
  name: app1
spec:
  generators:
    - git:
        repoURL: https://github.com/obeleh/argocd-namespaced-install.git
        revision: main
        directories:
          - path: argocd/workloads/app1/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: app1
    spec:
      project: app1
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/obeleh/argocd-namespaced-install.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'