---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app1
  name: argocd-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: app1
  name: argocd-role-binding
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd-custom-ns
#  - kind: ServiceAccount
#    name: argocd-applicationset-controller
#    namespace: argocd-custom-ns
#  - kind: ServiceAccount
#    name: argocd-repo-server
#    namespace: argocd-custom-ns
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd-custom-ns
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app1
  namespace: argocd-custom-ns
spec:
  destinations:
    - namespace: app1
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-argo-applications
  namespace: argocd-custom-ns
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: app1
    server: https://kubernetes.default.svc
  project: gitops-controller
  source:
    path: argocd/projects/app1/argo-applications
    targetRevision: main
    repoURL: https://github.com/obeleh/argocd-namespaced-install.git

---
