apiVersion: v1
kind: Namespace
metadata:
  name: argocd-custom-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd-custom-ns
  name: argocd-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd-custom-ns
  name: argocd-role-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-custom-ns
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-controller
  namespace: argocd-custom-ns
spec:
  destinations:
  - namespace: argocd-custom-ns
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
