apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# do not set namespace here, it would conflict with the namespace in the resources
resources:
- base
- app1-prerequisites.yaml
- app2-prerequisites.yaml
